# .streamlit/secrets.toml
[connections.neon]
# Use your NEON pooled endpoint; keep sslmode=require
url = "postgresql://neondb_owner:npg_OhX43czxQFvB@ep-lingering-moon-agl4xwbx-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require"